security:
    encoders:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            form_login:
                check_path: app_login
                login_path: app_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: app_homepage

            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31556952 # 1 year in seconds
                path: /
                #always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER