version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: guild
    ports: [5432]

  redis:
    image: redis:5-alpine
    ports: [6379]

  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]